[package]
name = "proof"
version = "0.1.0"
authors = ["julianknodt <julianknodt@gmail.com>"]

[dependencies]
csv = "1"

[[bin]]
name = "interpreter"
path = "src/bin/interpreter.rs"

[[bin]]
name = "compiler"
path = "src/bin/compiler.rs"

